### ISSUE TITLE
Connection to Maverick drops with error

### ISSUE THREAD

**Issue by eideroliveira** [everysight-maverick/sdk#13] opened 2024-11-27 19:52 UTC
I'm trying to run the sample apps, but whenever I try to connect to Maverick, it fails with "App auth error. ActivactionError", and logs show:

===-===-===-= refreshState => EV02A5 connected
------------** isProximityEnabled: false
------------** isGlassesTouchEnabled: false
===-===-===-= refreshState => EV02A5 disconnected

As I'm just running the sample apps, I have no idea of what is going on. I copied the sdk.key file to the Resources directory already

**Comment by eideroliveira** [comment] 2024-11-27 19:59
Actually, it seems that the other sample app was still running, there are more logs:

vs-sdk-log: 2024-11-27 16:46:12.927,log,EvsApp,Begin Auth process
evs-sdk-log: 2024-11-27 16:46:12.928,log,EvsResourceManager,Found none or more the one certificate, skip loading from assets
evs-sdk-log: 2024-11-27 16:46:12.929,log,EvsResourceManager,loadAndValidateApiKeyData app.key
evs-sdk-log: 2024-11-27 16:46:12.931,log,AuthService,there is no local app token
evs-sdk-log: 2024-11-27 16:46:12.931,log,EvsResourceManager,loadAndValidateApiKeyData sdk.2319004002A5.key
evs-sdk-error: 2024-11-27 16:46:12.932,error,AuthService,invalid local sdk token validation
evs-sdk-log: 2024-11-27 16:46:12.933,log,AuthService,there is no local sdk token
evs-sdk-log: 2024-11-27 16:46:12.933,log,EvsResourceManager,loadAndValidateApiKeyData sdk.key
evs-sdk-log: 2024-11-27 16:46:12.940,log,EvsResourceManager,loadAndValidateApiKeyData load data ok
evs-sdk-log: 2024-11-27 16:46:12.941,log,EvsResourceManager,loadAndValidateApiKeyData validateTokenAndGetClaims -> EvsApiTokenClaimsResult->  res:Ok claims:[scope=sdk]
evs-sdk-log: 2024-11-27 16:46:12.941,log,AuthService,validate SDK Token
evs-sdk-log: 2024-11-27 16:46:12.941,log,AuthService,validate SDK Token - OK
evs-sdk-log: 2024-11-27 16:46:12.942,log,AuthService,saveLastUsedApiToken = true
evs-sdk-log: 2024-11-27 16:46:12.943,log,AuthService,beginAuth: try get certificate from online server using api key isRefresh[needRefresh:false]
evs-sdk-log: 2024-11-27 16:46:12.943,log,AuthService,tryDownloadGlassesCertificate url:https://mavapi.everysight.com/maverick/certificate?serial=2319004002A5&namespace=com.eider.OtaHandling&appVersion=1.0 (1)
evs-sdk-warning: 2024-11-27 16:46:12.944,warning,EvsApp,Establishing connection...
evs-sdk-warning: 2024-11-27 16:46:12.957,warning,EvsApp,Establishing connection...
evs-sdk-warning: 2024-11-27 16:46:13.014,warning,EvsApp,Establishing connection...
evs-sdk-warning: 2024-11-27 16:46:13.104,warning,EvsApp,Establishing connection...
evs-sdk-warning: 2024-11-27 16:46:13.134,warning,EvsApp,Establishing connection...
evs-sdk-warning: 2024-11-27 16:46:13.225,warning,EvsApp,Establishing connection...
evs-sdk-warning: 2024-11-27 16:46:13.285,warning,EvsApp,Establishing connection...
evs-sdk-warning: 2024-11-27 16:46:13.315,warning,EvsApp,Establishing connection...
evs-sdk-error: 2024-11-27 16:46:13.328,error,EvsResourceManager,Error: invalid response
evs-sdk-error: 2024-11-27 16:46:13.329,error,AuthService,Server Error: invalid response
evs-sdk-error: 2024-11-27 16:46:13.329,error,AuthService,App auth Failed ActivationError
evs-sdk-log: 2024-11-27 16:46:13.330,log,AuthService,saveLastUsedApiToken = false
evs-sdk-log: 2024-11-27 16:46:13.331,log,CommService,disconnect
evs-sdk-log: 2024-11-27 16:46:13.331,log,CommService,disconnectInternal
evs-sdk-log: 2024-11-27 16:46:13.331,log,CommService,_autoConnect=false
evs-sdk-log: 2024-11-27 16:46:13.331,log,BtService,disconnectGlasses
evs-sdk-log: 2024-11-27 16:46:13.331,log,BtService,BLE cleanup (disconnect)
evs-sdk-log: 2024-11-27 16:46:13.331,log,BtService,--- unregisterNotifications
evs-sdk-log: 2024-11-27 16:46:13.331,log,BtService,--- unregisterNotifications started
evs-sdk-error: 2024-11-27 16:46:13.331,error,reportError,number of listeners: 6 code: ActivationError description:App auth Failed ActivationError
evs-sdk-log: 2024-11-27 16:46:13.332,log,CommService,onDisconnected
evs-sdk-log: 2024-11-27 16:46:13.332,log,EvsApp,onDisconnected
e

**Comment by feranf** [comment] 2024-11-28 16:08
Hi @eideroliveira,
We are checking the server logs. The SDK logs look as expected.

**Comment by feranf** [comment] 2024-11-28 16:45
Hi @eideroliveira,
I'm closing this issue as it is not a bug. I will contact you through our support system. In the meantime, please try again connecting the glasses - I think it will be OK now.

**Closed as completed by feranf** 2024-11-28 16:45 UTC
Labels: help wanted
